### ISSUE TITLE
Your site is blocked due SSL error

### ISSUE THREAD

**Issue by rubdottocom** [Dan-Q/twee2#20]
Firefox blocks twee2.danq.me and says that your certificate is valid only for:  www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

**Comment by Dan-Q** [comment]
Oh dear.

This happens because danq.me uses HSTS, so anybody who's visited danq.me or one of it's _other_ subdomains ends up with their browser refusing to display pages from danq.me subdomains over anything other than HTTPS. But GitHub Pages, where the site is hosted, only has SSL certificates for GitHub (of course).

**Comment by Dan-Q** [comment]
Okay, am trying a different approach, which will hopefully fix everything... once the DNS changes go through...

**Comment by Dan-Q** [comment]
Looks fine now.
